# Generated by Django 4.0 on 2022-01-07 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('details', models.CharField(max_length=255)),
                ('notify', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('age', models.IntegerField()),
                ('phone', models.BigIntegerField()),
                ('city', models.CharField(max_length=20)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
